services:
  - name: jeeimkg
    env:
      DJANGO_SETTINGS_MODULE: jeeimkg.settings.production
    buildCommand: bash ./build.sh
    startCommand: python manage.py runserver 0.0.0.0:$PORT

build:
  environment:
    PYTHON_VERSION: "3.8"
