# Generated by Django 4.1.6 on 2023-02-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
