# Generated by Django 4.1.6 on 2023-02-18 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_admin', '0003_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
